web:
    image: wordpress
    ports:
     - "80:80"
    links:
     - mysql
    volumes:
     - ".:/var/www/html"
mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
